### ISSUE TITLE
unknown command for the page name when adding new section

### ISSUE THREAD

**Issue by shawnchiao** [ObservedObserver/convertfast-ui#11]
when adding section, it shows this, have tried different names but still the same:
shawn@MacBook-Pro landingPage % npx convertfast-ui@latest page testpage add navbar
error: unknown command 'testpage'

**Comment by ObservedObserver** [comment]
do you have a `testpage` existed in your project, if not, you need to create it first.
```bash
npx convertfast-ui@latest page create testpage
```
