### ISSUE TITLE
Error on Initialization

### ISSUE THREAD

**Issue by mdp18** [ObservedObserver/convertfast-ui#4]
Getting this error upon initialization of convertfast-ui using React 18.3.1 and Node.js 20.11.1 using Windows to code. Looks like CP is being used as the command. Has this been coded out to work with Windows machines?

packages installed: `"packages": {
    "": {
      "name": "frontendv2",
      "version": "0.1.0",
      "dependencies": {
        "@radix-ui/react-icons": "^1.3.0",
        "@testing-library/jest-dom": "^5.17.0",
        "@testing-library/react": "^13.4.0",
        "@testing-library/user-event": "^13.5.0",
        "@types/jest": "^27.5.2",
        "@types/node": "^16.18.104",
        "@types/react": "^18.3.3",
        "@types/react-dom": "^18.3.0",
        "class-variance-authority": "^0.7.0",
        "clsx": "^2.1.1",
        "react": "^18.3.1",
        "react-dom": "^18.3.1",
        "react-scripts": "5.0.1",
        "tailwind-merge": "^2.4.0",
        "tailwindcss-animate": "^1.0.7",
        "typescript": "^4.9.5",
        "web-vitals": "^2.1.4"
      }
    },`

`
√ Are you using Next.js? ... no
file:///C:/Users/dev/AppData/Local/npm-cache/_npx/4e9aaba7860c907f/node_modules/execa/lib/return/final-error.js:6
        return new ErrorClass(message, options);
               ^

ExecaError: Command failed with exit code 1: cp -r "C:\Users\dev\AppData\Local\npm-cache\_npx\4e9aaba7860c907f\node_modules\convertfast-ui\assets\_convertfast" "D:\dev-playground\Pool\frontendv2\public"

'cp' is not recognized as an internal or external command,\r
operable program or batch file.
    at getFinalError (file:///C:/Users/dev/AppData/Local/npm-cache/_npx/4e9aaba7860c907f/node_modules/execa/lib/return/final-error.js:6:9)
    at makeError (file:///C:/Users/dev/AppData/Local/npm-cache/_npx/4e9aaba7860c907f/node_modules/execa/lib/return/result.js:108:16)      
    at getAsyncResult (file:///C:/Users/dev/AppData/Local/npm-cache/_npx/4e9aaba7860c907f/node_modules/execa/lib/methods/main-async.js:167:4)
    at handlePromise (file:///C:/Users/dev/AppData/Local/npm-cache/_npx/4e9aaba7860c907f/node_modules/execa/lib/methods/main-async.js:150:17)
    at async Command.<anonymous> (file:///C:/Users/dev/AppData/Local/npm-cache/_npx/4e9aaba7860c907f/node_modules/convertfast-ui/dist/index.js:2:1541) {
  shortMessage: 'Command failed with exit code 1: cp -r "C:\\Users\\dev\\AppData\\Local\\npm-cache\\_npx\\4e9aaba7860c907f\\node_modules\\convertfast-ui\\assets\\_convertfast" "D:\\dev-playground\\Pool\\frontendv2\\public"',
  command: 'cp -r C:\\Users\\dev\\AppData\\Local\\npm-cache\\_npx\\4e9aaba7860c907f\\node_modules\\convertfast-ui\\assets\\_convertfast D:\\dev-playground\\Pool\\frontendv2\\public',
  escapedCommand: 'cp -r "C:\\Users\\dev\\AppData\\Local\\npm-cache\\_npx\\4e9aaba7860c907f\\node_modules\\convertfast-ui\\assets\\_convertfast" "D:\\dev-playground\\Pool\\frontendv2\\public"',
  cwd: 'D:\\dev-playground\\Pool\\frontendv2',
  durationMs: 64.9074,
  failed: true,
  timedOut: false,
  isCanceled: false,
  isGracefullyCanceled: false,
  isTerminated: false,
  isMaxBuffer: false,
  isForcefullyTerminated: false,
  exitCode: 1,
  stdout: '',
  stderr: "'cp' is not recognized as an internal or external command,\r\n" +
    'operable program or batch file.',
  stdio: [
    undefined,
    '',
    "'cp' is not recognized as an internal or external command,\r\n" +
      'operable program or batch file.'
  ],
  ipcOutput: [],
  pipedFrom: []
}

Node.js v20.11.1
`

**Comment by ObservedObserver** [comment]
I tested on windows 11 and it seesm windows had already support copy command in some version. For early version or other platform, I replace the copy command in 0.0.7 with more cross platform implemenation, so you may have a try.
